apiVersion: v1
kind: Service
metadata:
  labels:
    app: localstack
  name: kinesis
spec:
  type: ClusterIP
  selector:
    app: localstack
  ports:
    - name: localstack
      protocol: TCP
      targetPort: 4568
      port: 4568